### PR TITLE
Feature/smartpoi

### PR DESCRIPTION
**Pull request by FRDavid**

### CODE REVIEW

**Comment by chicco785** [comment]
Hi David,
please provide as well:
- JSONSchema
- Example
- validation test (see [ci-test-weather.sh](https://github.com/smartsdk/dataModels/blob/master/test/ci-test-weather.sh))
- update the [.travis.yml](https://github.com/smartsdk/dataModels/blob/master/.travis.yml) to include the new validation test in the script section

Then if the Travis CI will be "green", I will accept the pull request.
Best,
Federico

**Comment by chicco785** [comment]
also, to facilitate the integration back to FIWARE repository, it is better to make a separate branch rather that an pull request directly to the master branch

**Comment by dherykw** [comment]
Hi Federico, 
Inheritance is a concept that the fiware guys are working on, we are doing the first try guided by Manuel, regarding to the branches, we aren't working in the master branch, we are working in a brach called /feature/smartpoi , We don't know  why are branches messed but right know we are working on the specs, once we will upload them we will fix it.

Thanks so mucho for the support
Regards Germán

**Comment by FRDavid** [comment]
As solicited, I close this PR and I will create a new branch from master where to put the PR.

**Pull request closed without merging**
