### PR TITLE
refactor: inclusion of items into category list

### PR DESCRIPTION
**Pull request by netzahdzc**
Is there a chance to extend current category list for those needed on the oHealth-Context data-model? In particular, I will like to include: medicalDevice and smartphone.

### CODE REVIEW

**Comment by chicco785** [comment]
hi netza i would also
- check the structure of the documents (see [User/ActivityType](https://github.com/smartsdk/dataModels/tree/master/User/ActivityType) e.g.)
- validate json schema with ajs (e.g. using the  [validate.sh](https://github.com/smartsdk/dataModels/blob/master/validate.sh) script)

federico

**Comment by chicco785** [comment]
I realize that userActivity, given that spec is draft may not be the best example. [User/Notification](https://github.com/smartsdk/dataModels/tree/master/User/Notification) and [Weather/WeatherObserved](https://github.com/smartsdk/dataModels/tree/master/Weather/WeatherObserved) are better examples.

**Comment by netzahdzc** [comment]
ok, thanks. I believe, the last commit (i.e., switching to FIWARE style...) presents a more suitable schema format, since I based it on Fiware examples. By the way, there are some some files into dataType directory that I haven't clean yet; please omit those for now; I will work on them along the week.

**Comment by netzahdzc** [comment]
Hi @chicco785, I just ran the validation mechanism by using the AJV Schema validator. The son schemas passes the evaluation when using **common-schema.json** as a reference structure. Thus, I still wondering why **travis-ci** still failing when building.

**Comment by chicco785** [comment]
Hi Netza, it's failing because I haven't yet properly configured it :) so
no worries!

**Comment by chicco785** [comment]
Hi, I have not properly set-up Travis CI.
I recommend to create a test file in test and adding it to the .travis.yml file.

**Comment by netzahdzc** [comment]
Hi there, I think the last commits are already on shape. Could you take a look please? If possible, could you commit those changes? I will like to continue tracking progress from this point.  Thanks in advance.

**Review by chicco785 — CHANGES_REQUESTED** [review]
hi netza probably your branch is not in synch with the master. rather than using validate.sh, i used directly ajv in the test, because this provide a better exit message

also please don't remove existing tests from .travis.yml 


#!/bin/sh

# Tests the Weather datamodels

testWeatherObserved(){
   result=`ajv compile --v5 -s Weather/WeatherObserved/schema.json -r common-schema.json -r geometry-schema.json -r Weather/weather-schema.json`
   assertEquals "schema Weather/WeatherObserved/schema.json is valid" "${result}"
   result=`ajv test --v5 -s Weather/WeatherObserved/schema.json -r common-schema.json -r geometry-schema.json -r Weather/weather-schema.json -d Weather/WeatherObserved/example.json --valid`
   assertEquals "Weather/WeatherObserved/example.json passed test" "${result}"
}

# load shunit2
. shunit2

**Comment by chicco785** [comment]
hi @netzahdzc, could you make the pull request toward the ohealt branch? before that, given the refactor, you will need to synch again with the master. thx, and sorry for the troubles.

**Comment by netzahdzc** [comment]
I just did a merge, but not sure it if worked appropriately. Please let me know if it does not work, so I can remove my local project and start a new one with this new structure

**Pull request closed without merging**
