### PR TITLE
feature/smartpoi

### PR DESCRIPTION
**Pull request by FRDavid**

### CODE REVIEW

**Comment by FRDavid** [comment]
Hi!

I tried to use ajv  to validate the schema.json file, but it raises the next error:

Hopu@DESKTOP-DAVID MINGW64 ~/Desktop/datamodels/new/dataModels (feature/smartpoi)
$ ajv validate -s PointOfInteraction/SmartPointOfInteraction/doc/schema.json -r common-schema.json -r geometry-schema.json -d PointOfInteraction/SmartPointOfInteraction/doc/example.json
schema geometry-schema.json is invalid
error: no schema with key or ref "http://json-schema.org/draft-04/schema#"

I tried also with an existing example:

Hopu@DESKTOP-DAVID MINGW64 ~/Desktop/datamodels/new/dataModels (feature/smartpoi)
$ ajv validate -s Parking/OffStreetParking/schema.json -r common-schema.json -r geometry-schema.json -d Parking/OffStreetParking/example.json
schema geometry-schema.json is invalid
error: no schema with key or ref "http://json-schema.org/draft-04/schema#"

Can someone explain me what I'm doing wrong?

BR,
David

**Comment by chicco785** [comment]
Hi David,
ajv was recently updated, to work with draft-schema-4, you need to use the old version:
```
npm install ajv@4.11.7
npm install -g ajv-cli@1.1.2
```

**Comment by FRDavid** [comment]
Thanks you @chicco785, I was able to correct and pass the schema/example files.

**Comment by FRDavid** [comment]
Hi! I closed the PR since 'smartpoi' data model has been introduced in the parent repository (fiware/datamodels), it will be obtained in the next pull from parent.

Thanks you @chicco785 and Federico

**Pull request closed without merging**
